// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtK41EOHvCVirLIZ-3MqHdgPix6HuKluQ',
    appId: '1:908955573673:web:150b36b5ddcb03f54578b8',
    messagingSenderId: '908955573673',
    projectId: 'test-fb7c0',
    authDomain: 'test-fb7c0.firebaseapp.com',
    databaseURL: 'https://test-fb7c0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'test-fb7c0.appspot.com',
    measurementId: 'G-622Y6RWKS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr8rKKXnJ5tzAC3Sffj7LLtOXEsiUUCx8',
    appId: '1:908955573673:android:a119f411840483034578b8',
    messagingSenderId: '908955573673',
    projectId: 'test-fb7c0',
    databaseURL: 'https://test-fb7c0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'test-fb7c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3iMJBqh1XxanBIPUXwL2fReGXvcg3vIg',
    appId: '1:908955573673:ios:252b1433441de9e14578b8',
    messagingSenderId: '908955573673',
    projectId: 'test-fb7c0',
    databaseURL: 'https://test-fb7c0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'test-fb7c0.appspot.com',
    iosBundleId: 'com.example.projekt1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3iMJBqh1XxanBIPUXwL2fReGXvcg3vIg',
    appId: '1:908955573673:ios:252b1433441de9e14578b8',
    messagingSenderId: '908955573673',
    projectId: 'test-fb7c0',
    databaseURL: 'https://test-fb7c0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'test-fb7c0.appspot.com',
    iosBundleId: 'com.example.projekt1',
  );
}
