import 'dart:async';
import 'package:firebase_database/firebase_database.dart';
import 'package:flutter/foundation.dart';
import 'package:geolocator/geolocator.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:hive/hive.dart';
import 'package:projekt1/function.dart';
import 'package:sensors_plus/sensors_plus.dart';
import 'package:tuple/tuple.dart';
import 'main.dart';
int flag=0;
String nazwa="Start";
double lati=0.0;
double longi=0.0;
bool isLoading=false;
bool send_flag=false;
bool toColud=false;
List<LatLng>poli=[];
Set<Polyline> polilines={};
bool istracking=false;
bool isvisible=true;
StreamSubscription<AccelerometerEvent>? accelerometerSubscription;
List<AccelerometerEvent> Accelerometer_data=[];
StreamSubscription<GyroscopeEvent>? gyroscopeSubscription;
List<GyroscopeEvent> Gyroscope_data=[];
final Stopwatch stopwatch = Stopwatch();
String note='';
List<double> cord_lati=[];
List<double> cord_long=[];List<List<double>> latLngList = [];
List<double> x_acc=[];
List<double> y_acc=[];
List<double> z_acc=[];

List<double> x_gyro=[];
List<double> y_gyro=[];
List<double> z_gyro=[];
List<double> time_a_acc=[];
List<double> time_a_gyro=[];
double a_x=0;
double a_y=0;
double a_z=0;

double g_x=0;
double g_y=0;
double g_z=0;
late Box box;
String opis='';
String date='';
  // var Box_GPS= Hive.openBox("GPS");
  // var Box_acc= Hive.openBox("acc");
  // var Box_gyro= Hive.openBox("gyro");